CREATE TABLE ALUNOS (
	ID_ALUNO				INT				NOT NULL,
	NOME					VARCHAR(200)	NOT NULL,
	DATA_NASCIMENTO			DATE			NOT NULL,
	SEXO					VARCHAR(1)		NULL, 
	DATA_CADASTRO			DATETIME		NOT NULL,
	LOGIN_CADASTRO			VARCHAR(15)		NOT NULL,
	PRIMARY KEY(ID_ALUNO),
	);

	
CREATE TABLE SITUACAO(
	ID_SITUACAO		INT				NOT NULL,
	SITUACAO		VARCHAR(25)		NOT NULL,
	DATA_CADASTRO	DATETIME,
	LOGIN_CADASTRO	VARCHAR(15),
	PRIMARY KEY(ID_SITUACAO)
	);

CREATE TABLE REGISTRO_PRESENCA(
	ID_TURMA INT NOT NULL,
	ID_ALUNO INT NOT NULL,
	ID_SITUACAO	INT NOT NULL,
	DATA_PRESENCA DATE,
	DATA_CADASTRO DATE NOT NULL,
	LOGIN_CADASTRO VARCHAR(15) NOT NULL


	);

CREATE TABLE CURSOS(
	ID_CURSO		INT			NOT NULL,
	NOME_CURSO		VARCHAR(200)NOT NULL,
	DATA_CADASTRO	DATE		NOT NULL,
	LOGIN_CADASTRO	DATE,
	PRIMARY KEY(ID_CURSO)
	);





CREATE TABLE TURMAS(
	ID_TURMA		INT NOT NULL,
	ID_ALUNO		INT NOT NULL,
	ID_CURSO		INT NOT NULL,
	VALOR_TURMA		NUMERIC(15,2) NOT NULL,
	DESCONTO		NUMERIC(3,2) NOT NULL,
	DATA_INICIO		DATE NOT NULL,
	DATA_TERMINO	DATE,
	DATA_CADASTRO	DATETIME NOT NULL,
	LOGIN_CADASTRO	VARCHAR(15),
	PRIMARY KEY(ID_TURMA),
	CONSTRAINT pk_ALUNOS_TURMAS FOREIGN KEY (ID_ALUNO)	REFERENCES ALUNOS(ID_ALUNO),
	CONSTRAINT PK_TURMAS_2_CURSO FOREIGN KEY(ID_CURSO)	REFERENCES CURSOS(ID_CURSO)
	);
